learnerConfig:
  # Learning algorithm
  algorithm: LSTAR

  # Oracle parameters
  randomSeed: 46346293
  runsPerQuery: 5
  eqOracle: WP_METHOD
  samplingThreshold: 0.8
  eqOracleMaxSteps: 1

  # Input alphabet parameters
  aggressorRows:
    - 0
    - 1
    - 2
  readCounts:
    - 50000
  bitFlips:
    - 1


  # Visualisation
  visualiseAllHypotheses: true
  visualiseLearntModel: true
  dotOutputPath: "/home/uhac206/"

adapterConfig:
  size: 0