learnerConfig:
  # Learning algorithm
  algorithm: LSTAR

  # Oracle parameters
  randomSeed: 46346293
  runsPerQuery: 10
  eqOracle: RANDOM_WALK
  samplingThreshold: 0.8
  eqOracleMaxSteps: 100

  # Input alphabet parameters
  minRow: 0
  maxRow: 1
  readCounts:
    - 1
  bitFlips:
    - 1


  # Visualisation
  visualiseAllHypotheses: false
  visualiseLearntModel: true
  dotOutputPath: "~"

adapterConfig:
  size: 0