learnerConfig:
  # Learning algorithm
  algorithm: LSTAR

  # Oracle parameters
  randomSeed: 46346293
  runsPerQuery: 10
  eqOracle: RANDOM_WALK
  samplingThreshold: 0.8
  eqOracleMaxSteps: 5

  # Input alphabet parameters
  minRow: 0
  maxRow: 4
  readCounts:
    - 1000
    - 10000
  bitFlips:
    - 1


  # Visualisation
  visualiseAllHypotheses: false
  visualiseLearntModel: true
  dotOutputPath: "/home/uhac206/"

adapterConfig:
  size: 0